name: Main

on:
  workflow_dispatch:
  
jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      chronos_job: firebase-schedule-backend-chronos-us-central1


    steps:   
      - name: Check if should deploy
        if: 'true'
        run: echo '::set-env name=DEPLOY:true'

      - name: Build
        run: echo Running job! $DEPLOY

      - name: Deploy
        if: ${{ $DEPLOY }}
        run: echo Deploying - $chronos_job
