name: Main

on: 
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      chronos_job: firebase-schedule-backend-chronos-us-central1

    steps:   
      - uses: haya14busa/action-cond@v1
        id: db_deployment
        with:
          cond: $(npm run print | grep 'poseidons')
          if_true: true
          if_false: false

      - name: Build
        run: echo Running job!

      - name: Deploy
        if: ${{ steps.db_deployment.outputs.value }}
        run: echo Deploying - $chronos_job
