name: Main

on:
  workflow_dispatch:
  
jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CHRONOS_JOB: firebase-schedule-backend-chronos-us-central1

    steps:
      - uses: actions/checkout@v2
      - name: Check if Chronos should be disabled
        run: |
          npm run print | grep 'poseidon' && echo '::set-env name=DISABLE_CHRONOS::true'

      - name: Build
        run: echo Running job!

      - name: Deploy
        run: |
          if [ "$DISABLE_CHRONOS" == "true" ]; then echo 'Disabling $CHRONOS_JOB';fi
          echo Deploying affected stuff
          if [ "$DISABLE_CHRONOS" == "true" ]; then echo 'Enabling $CHRONOS_JOB';fi
          
